# Generated by Django 4.1 on 2025-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
            ],
        ),
    ]
