# Generated by Django 4.2.20 on 2025-04-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='book_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='bookrecord',
            table='books_bookrecord',
        ),
    ]
